name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 3: Deploy to FTP server
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.abhi4136.odns.fr
          username: 06@01-web.formation-adapeco-
          password: aqFbABLGFz6wVhLe
          local-dir: dist/
          server-dir: /06/

          
